stages:
  - build
  - deploy

variables:
  SPRING_JAR_FILE: ${SPRING_JAR_PATH}

build-backend:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - echo "Building Spring Boot application JAR..."
    - mvn clean package -Dspring.profiles.active=prod -DskipTests
    - echo "Build complete. JAR expected at $SPRING_JAR_FILE"
    - ls -l $SPRING_JAR_FILE
  artifacts:
    paths:
      - $SPRING_JAR_FILE
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-backend:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  needs: ["build-backend"]
  script:
    - echo "Logging into Azure using Service Principal..."
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - echo "Setting Azure subscription..."
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - echo >
        "Deploying $SPRING_JAR_FILE to Azure Web App: $AZURE_BACKEND_APP_NAME in Resource Group: $AZURE_RESOURCE_GROUP..."
    - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_BACKEND_APP_NAME --src-path $SPRING_JAR_FILE --type jar
    - echo "Backend deployment initiated successfully."
    - az logout
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'